Cleanup repo layout
trixtur/CsBot pull request #2
Opened 2021-03-09 06:51 UTC by decriptor

2021-03-12 03:49 UTC, trixtur commented
Tried to run the debugger on the executable. I couldn't get the ConfigurationManager to read the config file anymore. Where does it need to go?

2021-03-18 02:39 UTC, trixtur requested changes
We need to be able to pull the configuration from the web service.

2021-03-18 03:31 UTC, decriptor commented on src/CsBot/IrcBotService.cs
> +		{
@trixtur Here is the code to download a configuration file. `WebClient` is dated and is replaced by httpclient

2021-03-19 03:49 UTC, trixtur approved these changes
Loaded it up and ran some commands. Looks good!

2021-03-19 05:47 UTC, merged